### ISSUE TITLE
MultiGPU and details inquiry

### ISSUE THREAD

**Issue by hanzh346** [ubc-tea/SADM-Longitudinal-Medical-Image-Generation#2] opened 2023-07-13 21:13 UTC
Hello,

Nice work!

I am also interested in implementing the model to my 4D brain dataset. Could you provide more details of your model code and training, e.g., what is your batch size number of epochs and feature number, do you have code for multi-GPU available?

Thank you

**Comment by wltjr1007** [comment] 2024-05-09 15:07
Sorry for the very late reply. I've completly lost track of this project, and I will get to uploading the code as soon as possible.

In the meantime, closing this issue as it is a duplicate of #1.

**Closed as completed by wltjr1007** 2024-05-09 15:07 UTC
